export const stockData = [
    {
      _id:"1",
      url:"https://i.pinimg.com/originals/b9/82/9f/b9829f910ca275dc08de8d8847d7769d.jpg",
      Content: "Muy Bueno",
      Brand: "Queko",
      Price: "80 USD",
    },
    {
      _id:"2",
      url:"https://images-na.ssl-images-amazon.com/images/I/81FgwJPKE7L.jpg",
      Content: "Square Inc",
      Brand: "SQ",
      Price: "45.28 USD",
    },
    {
      _id:"3",
      url:"https://i.pinimg.com/originals/b9/82/9f/b9829f910ca275dc08de8d8847d7769d.jpg",
      Content: "Square Inc",
      Brand: "Sam",
      Price: "23 USD",
    },
    {
      _id:"4",
      url:"https://images-na.ssl-images-amazon.com/images/I/81FgwJPKE7L.jpg",
      Content: "Build things awesome",
      Brand: "WALMART",
      Price: "5 USD",
    },
    {
      _id:"5",
      url:"https://i.pinimg.com/originals/b9/82/9f/b9829f910ca275dc08de8d8847d7769d.jpg",
      Content: "Pan",
      Brand: "Test",
      Price: "2 USD",
    },
    {
      _id:"6",
      url:"https://images-na.ssl-images-amazon.com/images/I/81FgwJPKE7L.jpg",
      Content: "Inc",
      Brand: "Tets 2",
      Price: "5 USD",
    },
    {
      _id:"4",
      url:"https://images-na.ssl-images-amazon.com/images/I/81FgwJPKE7L.jpg",
      Content: "Build things awesome",
      Brand: "WALMART",
      Price: "5 USD",
    },
    {
      _id:"5",
      url:"https://i.pinimg.com/originals/b9/82/9f/b9829f910ca275dc08de8d8847d7769d.jpg",
      Content: "Pan",
      Brand: "Test",
      Price: "2 USD",
    },
    {
      _id:"6",
      url:"https://images-na.ssl-images-amazon.com/images/I/81FgwJPKE7L.jpg",
      Content: "Inc",
      Brand: "Tets 2",
      Price: "5 USD",
    },
  ];